#!/usr/bin/env python3
"""
Lazy ETL Generator for SUSENAS Research Discovery Engine.

Generates reproducible, memory-efficient R scripts that selectively read only
the requested columns (via select / col_select) without loading entire datasets.
"""

import os
from pathlib import Path
from typing import List, Dict, Any, Optional

ETL_OUT_DIR = Path("etl/generated")

def generate_lazy_etl_r(
    rq_id: str,
    title: str,
    years: List[int],
    modules: List[str],
    year_columns: Dict[int, Dict[str, List[str]]],
    output_file: Optional[Path] = None
) -> Path:
    """Generate lazy R extraction script."""
    if output_file is None:
        ETL_OUT_DIR.mkdir(parents=True, exist_ok=True)
        output_file = ETL_OUT_DIR / f"{rq_id}_extract.R"

    r_code_lines = [
        "#!/usr/bin/env Rscript",
        "# ==============================================================================",
        f"# Auto-Generated Lazy ETL Script: {rq_id.upper()}",
        f"# Title: {title}",
        "# Generated by SUSENAS Research Discovery Engine",
        "# Principle: Selective column loading only (memory-efficient & token-saving)",
        "# ==============================================================================",
        "",
        "# 1. Environment & Path Setup",
        "suppressPackageStartupMessages({",
        "  library(data.table)",
        "  library(dplyr)",
        "})",
        "",
        "ROOT_DIR <- tryCatch(here::here(), error = function(e) getwd())",
        "DATA_ROOT <- file.path(ROOT_DIR, 'SUSENAS', 'JAWA BARAT')",
        "OUTPUT_DIR <- file.path(ROOT_DIR, 'output')",
        "dir.create(OUTPUT_DIR, showWarnings = FALSE, recursive = TRUE)",
        "",
        f"message('>> Starting Lazy ETL Extraction for: {rq_id}')",
        "dataset_list <- list()",
        ""
    ]

    for yr in years:
        r_code_lines.append("# ------------------------------------------------------------------------------")
        r_code_lines.append(f"# Year: {yr}")
        r_code_lines.append("# ------------------------------------------------------------------------------")
        r_code_lines.append(f"yr_{yr}_list <- list()")
        r_code_lines.append(f"yr_dir_{yr} <- file.path(DATA_ROOT, '{yr}')")
        r_code_lines.append(f"if (dir.exists(yr_dir_{yr})) {{")

        yr_mods = year_columns.get(yr, {})
        for mod, cols in yr_mods.items():
            cols_r_str = ', '.join([f"'{c}'" for c in sorted(list(set(cols)))])
            r_code_lines.append(f"  # Module: {mod}")
            r_code_lines.append(f"  mod_files_{yr}_{mod} <- list.files(yr_dir_{yr}, pattern = '{mod}.*\\\\.(csv|dbf)$', recursive = TRUE, full.names = TRUE, ignore.case = TRUE)")
            r_code_lines.append(f"  if (length(mod_files_{yr}_{mod}) > 0) {{")
            r_code_lines.append(f"    target_file <- mod_files_{yr}_{mod}[1]")
            r_code_lines.append(f"    message(sprintf('   [{yr}] Selective read %s: %d cols', basename(target_file), length(c({cols_r_str}))))")
            r_code_lines.append(f"    if (grepl('\\\\.csv$', target_file, ignore.case = TRUE)) {{")
            r_code_lines.append(f"      # Lazy CSV: only specified columns")
            r_code_lines.append(f"      dt <- data.table::fread(target_file, select = c({cols_r_str}), showProgress = FALSE)")
            r_code_lines.append(f"    }} else {{")
            r_code_lines.append(f"      # DBF: read and immediately select columns")
            r_code_lines.append(f"      raw_dbf <- foreign::read.dbf(target_file, as.is = TRUE)")
            r_code_lines.append(f"      valid_cols <- intersect(c({cols_r_str}), names(raw_dbf))")
            r_code_lines.append(f"      dt <- as.data.table(raw_dbf[, valid_cols, drop = FALSE])")
            r_code_lines.append(f"      rm(raw_dbf); gc(verbose = FALSE)")
            r_code_lines.append(f"    }}")
            r_code_lines.append(f"    yr_{yr}_list[['{mod}']] <- dt")
            r_code_lines.append(f"  }} else {{")
            r_code_lines.append(f"    message(sprintf('   [{yr}] File for module {mod} not found locally.'))")
            r_code_lines.append(f"  }}")

        r_code_lines.append(f"  # Join modules for year {yr} if multiple modules")
        r_code_lines.append(f"  if (length(yr_{yr}_list) > 0) {{")
        r_code_lines.append(f"    merged_yr_{yr} <- Reduce(function(x, y) merge(x, y, by = 'URUT', all.x = TRUE), yr_{yr}_list)")
        r_code_lines.append(f"    merged_yr_{yr}[, TAHUN := {yr}]")
        r_code_lines.append(f"    dataset_list[['{yr}']] <- merged_yr_{yr}")
        r_code_lines.append(f"  }}")
        r_code_lines.append(f"}} else {{")
        r_code_lines.append(f"  message(sprintf('   [{yr}] Directory not found locally: %s', yr_dir_{yr}))")
        r_code_lines.append(f"}}")
        r_code_lines.append("")

    r_code_lines.extend([
        "# ------------------------------------------------------------------------------",
        "# Combine Multi-Year Analytical Dataset",
        "# ------------------------------------------------------------------------------",
        "if (length(dataset_list) > 0) {",
        "  final_data <- rbindlist(dataset_list, fill = TRUE)",
        f"  out_file_rds <- file.path(OUTPUT_DIR, '{rq_id}_analytical_dataset.rds')",
        f"  out_file_csv <- file.path(OUTPUT_DIR, '{rq_id}_analytical_dataset.csv')",
        "  saveRDS(final_data, out_file_rds)",
        "  fwrite(head(final_data, 1000), out_file_csv) # sample preview",
        f"  message(sprintf('>> SUCCESS: Extracted %d rows across %d year(s). Saved to %s', nrow(final_data), length(dataset_list), out_file_rds))",
        "} else {",
        "  message('>> NOTICE: No local raw files found to extract. Download missing files from Google Drive first.')",
        "}",
        ""
    ])

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(r_code_lines) + "\n")

    return output_file

if __name__ == "__main__":
    test_rq = "rq001"
    test_cols = {
        2019: {"kor_rt": ["URUT", "R102", "R105", "WERT", "R1501", "R1502"], "kp_bp43": ["URUT", "FOOD", "KALORI_KAP"]},
        2020: {"kor_rt": ["URUT", "R102", "R105", "WERT", "R1601", "R1602"], "kp_bp43": ["URUT", "FOOD", "KALORI_KAP"]},
        2021: {"kor_rt": ["URUT", "R102", "R105", "WERT", "R1701", "R1702"], "kp_bp43": ["URUT", "FOOD", "KALORI_KAP"]},
        2022: {"kor_rt": ["URUT", "R102", "R105", "WERT", "R1701", "R1702"], "kp_bp43": ["URUT", "FOOD", "KALORI_KAP"]},
        2023: {"kor_rt": ["URUT", "R102", "R105", "WERT", "R1701", "R1702"], "kp_bp43": ["URUT", "FOOD", "KALORI_KAP"]}
    }
    p = generate_lazy_etl_r(test_rq, "Balita vs Kerawanan Pangan", [2019, 2020, 2021, 2022, 2023], ["kor_rt", "kp_bp43"], test_cols)
    print(f">> Generated: {p}")
